name: build-binaries
on: 
  release:
    types: published

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Running Tests
      run: go test ./...

    - name: Build
      run: |
        chmod +x build-all.sh
        ./build-all.sh
        zip --junk-paths markli.zip dist/*

    - name: Upload Release Asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./markli.zip
        asset_name: markli.zip
        asset_content_type: application/zip